name: Protect Production

on:
  pull_request:
    branches:
      - production

jobs:
  check-submitter:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check PR submitter
      run: |
        if [ ${GITHUB_ACTOR} != "foo" ]; then
          echo "::error ::Only CD4PE may submit changes to production. Please make your PR target master instead."
          exit 1
        fi
